name: container
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine3.14
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Step with docker
        uses: docker://node:17-buster
        with:
          entrypoint: '/bin/echo'
          args: "Hello world from docker"
      - name: Log node version
        uses: docker://node:17-buster
        with:
          entrypoint: /usr/local/bin/node
          args: -v
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:17-buster
        with:
          entrypoint: ./script.sh
          args: "Some string"
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:17-alpine3.14
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release